% *** constructProbabilityTree ***

% Counts frequencies of occurrence for sequences of characters using the
% corpus and stores them in a tree structure


% Clear workspace and console, close all figures
clear all;
close all;
clc;
tic
% Specify language
language = 'german';

% Specify depth of tree
treeDepth = 5;

%frequency of given sample:
freqsample = 'der'

% Load corpus
load([language, 'Clean.mat']);

%set a global variable for corpus length
global lengthcorpus;

lengthcorpus = length(corpus);

% Initialise tree
probTree = tree({'_', length(corpus)});

%corpus ='der_vorlesungen_schlafen,_ohne_dass_es_jemand_merkte,_ausgenommen_mein_freund_carlo_gabussi,_der_neben_mir_sass._o_traurige_jugend_und_suesse_erinnerung$$_$ii.$_die_sitzung_des_naechsten_tages_eroeffnete_$dr.$_zeunemann_mit_der_erklaerung,_eine_zeugin,_die_aus_ragusa_gekommen_sei,_habe_gebeten,_sofort_vernommen_zu_werden,_damit_sie_moeglichst_bald_zu_ihrer_familie_zurueckreisen_koenne._er_habe_um_so_weniger_anstoss_genommen,_ihrer_bitte_zu_willfahren,_als_er_sie_nicht_fuer_wichtig_halte_und_sie_nur_auf_ansuchen_des_verteidigers_zulasse._immerhin_werde_man_von_ihr_aufschluesse_ueber_die_beziehungen_des_angeklagten_zu_seiner_geschiedenen_frau_waehrend_der_ersten_zeit_seiner_ehe_erhalten._auf_seinen_wink_trat_eine_mittelgrosse_dame_ein,_die_mit_einer_ziegelroten_schabracke_behaengt_war_und_auf_ihrem_brandroten,_in_vielen_tollen_und_puffen_aufgesteckten_haar_einen_grossen,_von_einem_niagarafall_weisser_und_blauer_straussenfedern_ueberstuerzten_hut_trug._sie_trat_ein_paar_schritte_vorwaerts,_blieb_dann_stehen_und_sah_mit_suchenden_blicken_um_sich,_ein_erwartungsvolles_laecheln_auf_den_lippen._augenscheinlich_hatte_sie_sich_den_platz_des_angeklagten_beschreiben_lassen,_denn_dort_blieb_der_blick_haengen,_ohne_zunaechst_durch_das_ergebnis_seiner_forschung_befriedigt_zu_werden._ploetzlich_indessen_stiess_sie_einen_schrei_aus,_rief_mit_kreischender_stimme$_$dodo$$_und_lief_mit_ausgestreckten_armen_auf_deruga_zu._sie_hatte_ihn_jedoch_nicht_erreicht,_als_der_gerichtsdiener,_der_sie_hereingefuehrt_hatte,_ihrer_habhaft_wurde_und_sie_vor_den_kleinen_tisch_im_angesicht_der_versammelten_richter_stellte,_wo_sie_den_eid_zu_leisten_hatte._$entschuldigen_sie,$_sagte_sie_schluchzend,_indem_sie_ihr_taschentuch_hervorzog,_$aber_das_war_zu_viel_fuer_mich._dies_wiedersehen_nach_so_viel_jahren$_die_veraenderung$_und_im_grunde_doch_dasselbe_liebe,_naerrische_gesicht$_wenn_sie_mir_eine_pfanne_mit_gluehenden_kohlen_herstellen,_herr_praesident,_so_schwoere_ich_ihnen,_ich_halte_die_hand_hinein,_um_seine_unschuld_zu_beweisen$$_$die_sache_ist_leider_nicht_so_einfach,$_sagte_$dr.$_zeunemann_mit_wohlwollender_ueberlegenheit._$hingegen_koennen_sie_uns_unsere_arbeit_sehr_erleichtern_und_dem_angeklagten_nuetzen,_wenn_sie,_was_sie_zu_sagen_haben,_kurz,_klar_und_folgerichtig_sagen._sie_heissen_rosine_schmid_geborene_vogelfrei,_sind_hauptmannsgattin_und_vierundvierzig_jahre_alt$$_$jawohl,$_sagte_die_dame,_$ich_gehoere_nicht_zu_denjenigen_frauen,_die_sich_ihres_alters_schaemen._uebrigens_tun_die_maenner_auch,_was_sie_koennen,_um_jung_zu_erscheinen,_besonders_beim_militaer,_und_wuerden_es_noch_mehr_tun,_wenn_so_viel_fuer_sie_davon_abhinge_wie_fuer_uns_frauen.$_$frau_hauptmann,$_sagte_der_vorsitzende,_$sie_kennen_den_angeklagten_sigismondo_enea_deruga,_sind_aber_nicht_mit_ihm_verwandt._wollen_sie_so_gut_sein_und_mit_vermeidung_alles_ueberfluessigen_erzaehlen,_wann_und_unter_welchen_umstaenden_sie_ihn_kennenlernten$$_$mit_vergnuegen_will_ich_das,$_sagte_frau_hauptmann_schmid_lebhaft._$alles_will_ich_sagen,_was_ich_weiss,_denn_dazu_bin_ich_ja_hergekommen._und_wenn_ich_ans_ende_der_welt_reisen_muesste,_sagte_ich_zu_meinem_mann,_ich_taete_es,_um_dem_dodo_aus_der_patsche_zu_helfen._das_hat_er_um_mich_verdient,_so_lieb_und_gut_wie_er_immer_war._und_getan_hat_er_es_auch_nicht,_denn_wenn_er_auch_etwas_toll_und_originell_war,_der_topf_voll_maeuse,_gemordet_hat_er_sicherlich_keinen_christenmenschen_und_am_wenigsten_die_gute_seele,_seine_frau.$_$wie_kommt_es,_dass_sie_den_angeklagten_einen_topf_voll_maeuse_nennen$$_fragte_$dr.$_zeunemann._$so_nennt_man_doch,$_erklaerte_frau_schmid,_$die_figur,_die_bei_den_feuerwerken_gewoehnlich_zuletzt_kommt,_wo_es_so_kracht_und_prasselt,_dass_man_glaubt,_einen_feuerspeienden_berg_vor_sich_zu_haben._es_war_eine_art_kosenamen,_den_seine_frau_ihm_gegeben_hatte,_weil_er_zuweilen_anfaelle_von_wut_bekam,_wo_er_rauch_und_feuer_spuckte,_so_dass_sie_sich_vor_ihm_fuerchtete.$_$sonderbarer_kosename,$_meinte_der_vorsitzende._$ach,_herr_praesident,$_sagte_die_frau_hauptmann_lachend,_$er_meinte_es_ja_im_grunde_nicht_boese,_so_wenig_wie_ein_topf_voll_maeuse_gefaehrlich_ist._darum_passte_der_name_gerade_so_gut,_und_wir_nannten_ihn_alle_so,_obgleich_es_sich_fuer_mich,_so_ein_junges_maedchen_wie_ich_war,_kaum_recht_schickte.$_$ich_bitte_zu_beachten,$_sagte_der_staatsanwalt,_$dass_nach_aussage_der_zeugin_die_damalige_frau_deruga_sich_vor_ihrem_mann_fuerchtete.$_frau_hauptmann_schmid_drehte_sich_schnell_nach_dem_sprecher_herum_und_sagte,_waehrend_ihr_das_blut_ins_gesicht_stieg$_$wenn_sie_glauben,_sie_haetten_damit_einen_vorteil_ueber_den_herrn_doktor_gewonnen,_dass_ich_gesagt_habe,_er_sei_aufbrausend,_so_sind_sie_gewaltig_im_irrtum._die_aufbrausenden_sind_die_schlimmsten_nicht,_und_das_sagt_ja_auch_das_sprichwort$_hunde,_die_bellen,_beissen_nicht._ich_habe_oft_zu_meinem_manne_gesagt$_$meinetwegen_moechtest_du_schimpfen_und_fluchen,_ja,_sogar_in_gottes_namen_zuschlagen,_nur_das_maulen_und_scheelblicken,_das_brummen_und_nachtragen,_das_ist_mir_zuwider,_und_ich_glaube,_dass_einer,_dem_es_nie_ueberlaeuft,_das_herz_nicht_auf_dem_rechten_flecke_hat.$$_der_vorsitzende_machte_eine_abschliessende_handbewegung';


% Iterate over entire corpus
for index = 1 : (length(corpus) - treeDepth+1)
    

    % Extract a n-element long sample of the corpus
    %es wird das element das an der stelle "index" bis zum element
    %"index+treedepth-1" extrahiert

    sample = corpus(index:index+treeDepth-1);
    
    % Append sample to tree
    probTree = appendAndIncrement(probTree, sample, 1);
    
end

for i=2:length(probTree.Node)
string(i) = probTree.Node{i,1}{1,3};
i;
end

getFrequency(probTree,freqsample,1)

%max(string)
toc

% Save variables to file
save(['../Corpora/', fileName(1:end-4), 'ProbabilityTree'], ...
    'probTree', 'alphabet', 'treeDepth', 'dictionary', 'language', ...
    'keySet', 'symbolSet', 'nKeys'...
    );